// =============================================================================
// Vocabulario SQL por motor, solo datos y en MAYÚSCULAS: RESERVADAS (¿hay que citar?), PALABRAS_CLAVE
// (autocompletado), VERBOS_AVISO (inicio de sentencia nueva, lista corta a propósito) y los comandos de
// SQL*Plus. Son listas distintas y no se mezclan: responden a preguntas distintas. Neutral y ES2020.
// Decisiones: docs/decisiones/bd/sql-dialectos-como-tabla.md
// =============================================================================

import { deDialecto, type DialectoSql } from './dialectosSql.ts'
import { conjunto } from './conjuntoSql.ts'

/**
 * Verbos que abren una sentencia nueva. Solo para el aviso «¿falta ;?»: la
 * clasificación tiene su propia tabla, mucho más larga.
 */
export const VERBOS_AVISO: ReadonlySet<string> = conjunto(`
  SELECT INSERT UPDATE DELETE MERGE WITH CREATE DROP ALTER TRUNCATE
  GRANT REVOKE COMMIT ROLLBACK CALL
`)

/**
 * Verbos del aviso «¿falta ;?» que suma cada dialecto a `VERBOS_AVISO`. En
 * SQL Server dos sentencias sin `;` se EJECUTAN JUNTAS (`sinSeparadorSeEjecutanJuntas`), así
 * que el aviso vale más y se miran también sus verbos propios: todos RESERVADOS en T-SQL
 * (no pueden ser un alias ni un nombre sin corchetes), salvo THROW, que por eso exige `;`
 * delante (102). Con EXEC en la lista, `INSERT … EXEC p` cuenta EXEC como la consulta
 * principal del INSERT (ver `avisosSql.ts`). Vacía en los demás: no cambian.
 */
export const VERBOS_AVISO_DIALECTO: Readonly<Record<DialectoSql, ReadonlySet<string>>> = {
  oracle: new Set<string>(),
  postgres: new Set<string>(),
  sqlite: new Set<string>(),
  sqlserver: conjunto(`
    EXEC EXECUTE DECLARE PRINT THROW RAISERROR USE IF WHILE BEGIN WAITFOR DBCC KILL BACKUP
    RESTORE BULK DENY SAVE
  `)
}

/**
 * Palabras tras las cuales una línea que empieza por un verbo es CONTINUACIÓN
 * de la misma sentencia (`UNION` + `SELECT`, `FOR` + `UPDATE`, `DO` + `UPDATE`
 * en un ON CONFLICT, `THEN` + `INSERT` en un MERGE…). Si la línea anterior acaba
 * en una de estas, no falta ningún `;`.
 */
export const PALABRAS_CONECTORAS: ReadonlySet<string> = conjunto(`
  AS UNION ALL INTERSECT MINUS EXCEPT DISTINCT FOR THEN ELSE GRANT ON DO
  INSTEAD ALSO BEFORE AFTER OR AND NOT INTO FROM WHERE SET BY IN EXISTS IS
  LIKE ILIKE BETWEEN WHEN JOIN USING VALUES RETURNING WITH RECURSIVE TABLE
  VIEW OF EACH ROW STATEMENT EXECUTE PROCEDURE FUNCTION LOOP BEGIN DECLARE
  IF ELSIF CASE EXPLAIN ANALYZE VERBOSE COMMIT SELECT HAVING ORDER GROUP
  LATERAL ANY SOME TO MATCHED
`)

/** Reservadas de Oracle (V$RESERVED_WORDS, RESERVED='Y'). */
const RESERVADAS_ORACLE = conjunto(`
  ACCESS ADD ALL ALTER AND ANY AS ASC AUDIT BETWEEN BY CHAR CHECK CLUSTER
  COLUMN COMMENT COMPRESS CONNECT CREATE CURRENT DATE DECIMAL DEFAULT DELETE
  DESC DISTINCT DROP ELSE EXCLUSIVE EXISTS FILE FLOAT FOR FROM GRANT GROUP
  HAVING IDENTIFIED IMMEDIATE IN INCREMENT INDEX INITIAL INSERT INTEGER
  INTERSECT INTO IS LEVEL LIKE LOCK LONG MAXEXTENTS MINUS MLSLABEL MODE
  MODIFY NOAUDIT NOCOMPRESS NOT NOWAIT NULL NUMBER OF OFFLINE ON ONLINE
  OPTION OR ORDER PCTFREE PRIOR PUBLIC RAW RENAME RESOURCE REVOKE ROW ROWID
  ROWNUM ROWS SELECT SESSION SET SHARE SIZE SMALLINT START SUCCESSFUL
  SYNONYM SYSDATE TABLE THEN TO TRIGGER UID UNION UNIQUE UPDATE USER
  VALIDATE VALUES VARCHAR VARCHAR2 VIEW WHENEVER WHERE WITH
  BEGIN DECLARE END EXCEPTION FUNCTION PROCEDURE PACKAGE TYPE
`)

/** Reservadas de PostgreSQL ("reserved" y "reserved (can be function or type)"). */
const RESERVADAS_POSTGRES = conjunto(`
  ALL ANALYSE ANALYZE AND ANY ARRAY AS ASC ASYMMETRIC BOTH CASE CAST CHECK
  COLLATE COLUMN CONSTRAINT CREATE CURRENT_CATALOG CURRENT_DATE CURRENT_ROLE
  CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER DEFAULT DEFERRABLE DESC
  DISTINCT DO ELSE END EXCEPT FALSE FETCH FOR FOREIGN FROM GRANT GROUP
  HAVING IN INITIALLY INTERSECT INTO LATERAL LEADING LIMIT LOCALTIME
  LOCALTIMESTAMP NOT NULL OFFSET ON ONLY OR ORDER PLACING PRIMARY REFERENCES
  RETURNING SELECT SESSION_USER SOME SYMMETRIC SYSTEM_USER TABLE THEN TO
  TRAILING TRUE UNION UNIQUE USER USING VARIADIC WHEN WHERE WINDOW WITH
  AUTHORIZATION BINARY COLLATION CONCURRENTLY CROSS CURRENT_SCHEMA FREEZE
  FULL ILIKE INNER IS ISNULL JOIN LEFT LIKE NATURAL NOTNULL OUTER OVERLAPS
  RIGHT SIMILAR TABLESAMPLE VERBOSE
`)

/**
 * Palabras clave de SQLite (la lista de su documentación, «SQLite Keywords»). SQLite deja
 * usar muchas como nombre sin comillas (su analizador tiene un «fallback»), pero cuáles
 * depende del contexto y de la versión: se toman TODAS como reservadas, porque citar de
 * más es inofensivo y citar de menos rompe la sentencia (ver la cabecera).
 */
const RESERVADAS_SQLITE = conjunto(`
  ABORT ACTION ADD AFTER ALL ALTER ALWAYS ANALYZE AND AS ASC ATTACH AUTOINCREMENT
  BEFORE BEGIN BETWEEN BY CASCADE CASE CAST CHECK COLLATE COLUMN COMMIT CONFLICT
  CONSTRAINT CREATE CROSS CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP
  DATABASE DEFAULT DEFERRABLE DEFERRED DELETE DESC DETACH DISTINCT DO DROP EACH ELSE
  END ESCAPE EXCEPT EXCLUDE EXCLUSIVE EXISTS EXPLAIN FAIL FILTER FIRST FOLLOWING FOR
  FOREIGN FROM FULL GENERATED GLOB GROUP GROUPS HAVING IF IGNORE IMMEDIATE IN INDEX
  INDEXED INITIALLY INNER INSERT INSTEAD INTERSECT INTO IS ISNULL JOIN KEY LAST LEFT
  LIKE LIMIT MATCH MATERIALIZED NATURAL NO NOT NOTHING NOTNULL NULL NULLS OF OFFSET
  ON OR ORDER OTHERS OUTER OVER PARTITION PLAN PRAGMA PRECEDING PRIMARY QUERY RAISE
  RANGE RECURSIVE REFERENCES REGEXP REINDEX RELEASE RENAME REPLACE RESTRICT
  RETURNING RIGHT ROLLBACK ROW ROWS SAVEPOINT SELECT SET TABLE TEMP TEMPORARY THEN
  TIES TO TRANSACTION TRIGGER UNBOUNDED UNION UNIQUE UPDATE USING VACUUM VALUES VIEW
  VIRTUAL WHEN WHERE WINDOW WITH WITHOUT
`)

/**
 * SQL Server: las «Reserved keywords» de Transact-SQL de Microsoft Learn
 * (las que un identificador solo puede usar entre corchetes o comillas dobles; medido: OPEN
 * y CLOSE sin corchetes dan el 156). No se suman las «ODBC reserved keywords» de la misma
 * página: el servidor las acepta sin citar. Es también la lista con la que el clasificador
 * de T-SQL sabe que una palabra de escritura NO puede ser un identificador sin citar (ver
 * `REGLAS.sqlserver`).
 */
const RESERVADAS_SQLSERVER = conjunto(`
  ADD ALL ALTER AND ANY AS ASC AUTHORIZATION BACKUP BEGIN BETWEEN BREAK BROWSE BULK BY
  CASCADE CASE CHECK CHECKPOINT CLOSE CLUSTERED COALESCE COLLATE COLUMN COMMIT COMPUTE
  CONSTRAINT CONTAINS CONTAINSTABLE CONTINUE CONVERT CREATE CROSS CURRENT CURRENT_DATE
  CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DBCC DEALLOCATE DECLARE
  DEFAULT DELETE DENY DESC DISK DISTINCT DISTRIBUTED DOUBLE DROP DUMP ELSE END ERRLVL
  ESCAPE EXCEPT EXEC EXECUTE EXISTS EXIT EXTERNAL FETCH FILE FILLFACTOR FOR FOREIGN
  FREETEXT FREETEXTTABLE FROM FULL FUNCTION GOTO GRANT GROUP HAVING HOLDLOCK IDENTITY
  IDENTITY_INSERT IDENTITYCOL IF IN INDEX INNER INSERT INTERSECT INTO IS JOIN KEY KILL
  LEFT LIKE LINENO LOAD MERGE NATIONAL NOCHECK NONCLUSTERED NOT NULL NULLIF OF OFF
  OFFSETS ON OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML OPTION OR ORDER OUTER
  OVER PERCENT PIVOT PLAN PRECISION PRIMARY PRINT PROC PROCEDURE PUBLIC RAISERROR READ
  READTEXT RECONFIGURE REFERENCES REPLICATION RESTORE RESTRICT RETURN REVERT REVOKE
  RIGHT ROLLBACK ROWCOUNT ROWGUIDCOL RULE SAVE SCHEMA SECURITYAUDIT SELECT
  SEMANTICKEYPHRASETABLE SEMANTICSIMILARITYDETAILSTABLE SEMANTICSIMILARITYTABLE
  SESSION_USER SET SETUSER SHUTDOWN SOME STATISTICS SYSTEM_USER TABLE TABLESAMPLE
  TEXTSIZE THEN TO TOP TRAN TRANSACTION TRIGGER TRUNCATE TRY_CONVERT TSEQUAL UNION
  UNIQUE UNPIVOT UPDATE UPDATETEXT USE USER VALUES VARYING VIEW WAITFOR WHEN WHERE WHILE
  WITH WITHIN WRITETEXT
`)

export const RESERVADAS: Readonly<Record<DialectoSql, ReadonlySet<string>>> = {
  oracle: RESERVADAS_ORACLE,
  postgres: RESERVADAS_POSTGRES,
  sqlite: RESERVADAS_SQLITE,
  sqlserver: RESERVADAS_SQLSERVER
}

const CLAVE_COMUNES = `
  SELECT FROM WHERE AND OR NOT IN EXISTS BETWEEN LIKE IS NULL AS ON JOIN
  INNER LEFT RIGHT FULL OUTER CROSS NATURAL USING GROUP BY HAVING ORDER ASC
  DESC NULLS FIRST LAST DISTINCT ALL ANY SOME UNION INTERSECT CASE WHEN THEN
  ELSE END INSERT INTO VALUES UPDATE SET DELETE MERGE MATCHED CREATE REPLACE
  TABLE VIEW INDEX SEQUENCE ALTER DROP TRUNCATE COMMENT GRANT REVOKE COMMIT
  ROLLBACK SAVEPOINT WITH RECURSIVE PRIMARY KEY FOREIGN REFERENCES CONSTRAINT
  CHECK DEFAULT UNIQUE COUNT SUM AVG MIN MAX COALESCE NULLIF CAST OVER
  PARTITION ROW_NUMBER RANK DENSE_RANK LAG LEAD FETCH OFFSET ROWS ONLY
  CURRENT_DATE CURRENT_TIMESTAMP UPPER LOWER TRIM LENGTH ROUND EXTRACT
  FUNCTION PROCEDURE TRIGGER TYPE SCHEMA CALL EXPLAIN LOCK LATERAL
`

/** Palabras clave que ofrece el autocompletado. */
export const PALABRAS_CLAVE: Readonly<Record<DialectoSql, readonly string[]>> = {
  oracle: Array.from(
    conjunto(
      CLAVE_COMUNES +
        `
      MINUS NVL NVL2 DECODE TO_CHAR TO_DATE TO_NUMBER TO_TIMESTAMP TRUNC SUBSTR
      INSTR LPAD RPAD LTRIM RTRIM LISTAGG WITHIN SYSDATE SYSTIMESTAMP ROWNUM
      ROWID LEVEL CONNECT PRIOR START DUAL PACKAGE BODY SYNONYM PUBLIC BEGIN
      DECLARE EXCEPTION RETURN RETURNING LOOP WHILE FOR IF ELSIF EXIT CURSOR
      OPEN CLOSE BULK COLLECT FORALL PRAGMA EXECUTE IMMEDIATE NUMBER VARCHAR2
      NVARCHAR2 CHAR DATE TIMESTAMP INTERVAL CLOB BLOB RAW INTEGER SESSION
      CURRENT_SCHEMA MODIFY RENAME
    `
    )
  ),
  postgres: Array.from(
    conjunto(
      CLAVE_COMUNES +
        `
      EXCEPT LIMIT ILIKE RETURNING CONFLICT DO NOTHING ARRAY ARRAY_AGG
      STRING_AGG JSON_AGG JSONB JSON TEXT VARCHAR INTEGER BIGINT SMALLINT
      NUMERIC BOOLEAN TRUE FALSE SERIAL BIGSERIAL UUID DATE TIMESTAMP
      TIMESTAMPTZ INTERVAL NOW DATE_TRUNC GENERATE_SERIES ANALYZE VACUUM SHOW
      SEARCH_PATH WINDOW FILTER MATERIALIZED REFRESH CONCURRENTLY EXTENSION
      DOMAIN ENUM TEMPORARY UNLOGGED INHERITS OWNER RENAME COLUMN ADD BEGIN
      START TRANSACTION IF
    `
    )
  ),
  // SQLite: lista PROPIA, sin `CLAVE_COMUNES`, que trae verbos que SQLite
  // no tiene (MERGE, TRUNCATE, GRANT, SEQUENCE, CALL…) y que el autocompletado no debe
  // ofrecer. Sin ATTACH/DETACH ni load_extension: están cerrados siempre. Lista de UX,
  // como las otras; el grupo SQL la afina.
  sqlite: Array.from(
    conjunto(`
      SELECT FROM WHERE AND OR NOT IN EXISTS BETWEEN LIKE GLOB REGEXP IS NULL AS ON
      JOIN INNER LEFT RIGHT FULL OUTER CROSS NATURAL USING GROUP BY HAVING ORDER ASC
      DESC NULLS FIRST LAST DISTINCT ALL UNION INTERSECT EXCEPT CASE WHEN THEN ELSE
      END INSERT INTO VALUES UPDATE SET DELETE REPLACE CREATE TABLE VIEW INDEX
      TRIGGER VIRTUAL TEMP TEMPORARY IF ALTER RENAME COLUMN ADD DROP WITH RECURSIVE
      PRIMARY KEY FOREIGN REFERENCES CONSTRAINT CHECK DEFAULT UNIQUE COLLATE
      AUTOINCREMENT WITHOUT ROWID STRICT GENERATED ALWAYS STORED CONFLICT DO NOTHING
      RETURNING LIMIT OFFSET OVER PARTITION FILTER WINDOW ROW_NUMBER RANK DENSE_RANK
      LAG LEAD COUNT SUM TOTAL AVG MIN MAX COALESCE IFNULL NULLIF IIF CAST TYPEOF
      UPPER LOWER TRIM LTRIM RTRIM LENGTH SUBSTR INSTR PRINTF FORMAT ROUND ABS
      GROUP_CONCAT STRING_AGG JSON JSON_EXTRACT JSON_OBJECT JSON_ARRAY JSON_EACH
      JSON_TREE DATE TIME DATETIME JULIANDAY STRFTIME UNIXEPOCH INTEGER REAL TEXT
      BLOB NUMERIC BEGIN DEFERRED IMMEDIATE EXCLUSIVE TRANSACTION COMMIT ROLLBACK
      SAVEPOINT RELEASE PRAGMA EXPLAIN QUERY PLAN ANALYZE VACUUM REINDEX
    `)
  ),
  // SQL Server: lista PROPIA, como la de SQLite: `CLAVE_COMUNES` trae
  // verbos que T-SQL no tiene (CALL, EXPLAIN, LATERAL, NULLS FIRST, RECURSIVE, COMMENT). Lista
  // de UX, no gramática; el grupo SQL la afina.
  sqlserver: Array.from(
    conjunto(`
      SELECT TOP PERCENT TIES FROM WHERE AND OR NOT IN EXISTS BETWEEN LIKE IS NULL AS ON
      JOIN INNER LEFT RIGHT FULL OUTER CROSS APPLY GROUP BY HAVING ORDER ASC DESC DISTINCT
      ALL ANY SOME UNION INTERSECT EXCEPT CASE WHEN THEN ELSE END INSERT INTO VALUES UPDATE
      SET DELETE MERGE MATCHED OUTPUT INSERTED DELETED CREATE ALTER DROP TRUNCATE TABLE VIEW
      INDEX SEQUENCE SYNONYM SCHEMA PROCEDURE PROC FUNCTION TRIGGER TYPE RETURNS RETURN
      WITH PRIMARY KEY FOREIGN REFERENCES CONSTRAINT CHECK DEFAULT UNIQUE IDENTITY
      CLUSTERED NONCLUSTERED OFFSET ROWS FETCH NEXT ONLY OVER PARTITION ROW_NUMBER RANK
      DENSE_RANK NTILE LAG LEAD COUNT COUNT_BIG SUM AVG MIN MAX COALESCE NULLIF ISNULL IIF
      CAST CONVERT TRY_CAST TRY_CONVERT FORMAT UPPER LOWER LTRIM RTRIM LEN DATALENGTH
      SUBSTRING CHARINDEX REPLACE CONCAT STRING_AGG STRING_SPLIT GETDATE SYSDATETIME
      SYSDATETIMEOFFSET DATEADD DATEDIFF DATEPART DATENAME EOMONTH NEWID SCOPE_IDENTITY
      OBJECT_ID OBJECT_NAME DB_NAME SCHEMA_NAME PIVOT UNPIVOT NOLOCK INT BIGINT SMALLINT
      TINYINT BIT DECIMAL NUMERIC MONEY FLOAT REAL CHAR VARCHAR NCHAR NVARCHAR MAX DATE
      TIME DATETIME DATETIME2 DATETIMEOFFSET UNIQUEIDENTIFIER VARBINARY XML DECLARE BEGIN
      TRY CATCH THROW RAISERROR PRINT IF WHILE BREAK CONTINUE GOTO WAITFOR DELAY TRAN
      TRANSACTION COMMIT ROLLBACK SAVE EXEC EXECUTE USE GO GRANT REVOKE DENY
      NOCOUNT XACT_ABORT LOCK_TIMEOUT ISOLATION LEVEL READ UNCOMMITTED COMMITTED SNAPSHOT
      SERIALIZABLE STATISTICS IO ON OFF ADD COLUMN CURSOR OPEN CLOSE DEALLOCATE FOR JSON
      XML PATH OPENJSON JSON_VALUE JSON_QUERY ISJSON VALUE NOWAIT
    `)
  )
}

/**
 * Comandos que SQL*Plus interpreta él mismo (con sus abreviaturas habituales).
 * Solo cuentan como primera palabra de una línea FUERA de un bloque PL/SQL:
 * dentro, `EXIT WHEN` y `EXECUTE IMMEDIATE` son PL/SQL.
 * `SET` no está: depende de la palabra que le sigue (ver OPCIONES_SET_SQLPLUS).
 * Se excluyen las abreviaturas de una letra (`L`, `R`, `A`…): chocan con
 * cualquier identificador y nadie las escribe en un script.
 */
export const COMANDOS_SQLPLUS: ReadonlySet<string> = conjunto(`
  ACCEPT ACC APPEND ARCHIVE ATTRIBUTE BREAK BRE BTITLE CHANGE CLEAR CL COLUMN
  COL COMPUTE COMP CONNECT CONN COPY DEFINE DEF DEL DESCRIBE DESC DISCONNECT
  DISC EDIT ED EXECUTE EXEC EXIT GET HELP HOST INPUT LIST PASSWORD PAUSE PRINT
  PROMPT PRO QUIT RECOVER REMARK REM REPFOOTER REPHEADER RUN SAVE SHOW SHO
  SHUTDOWN SPOOL SPO START STA STARTUP STORE TIMING TTITLE UNDEFINE VARIABLE
  VAR WHENEVER XQUERY
`)

/** Comandos que se traducen a un bloque anónimo en vez de descartarse. */
export const COMANDOS_EXEC: ReadonlySet<string> = conjunto('EXEC EXECUTE')

/** Opciones de `SET` que son de SQL*Plus (con abreviaturas). */
export const OPCIONES_SET_SQLPLUS: ReadonlySet<string> = conjunto(`
  APPINFO APPI ARRAYSIZE ARRAY AUTOCOMMIT AUTO AUTOPRINT AUTOP AUTORECOVERY
  AUTOTRACE AUTOT BLOCKTERMINATOR BLO CMDSEP CMDS COLINVISIBLE COLSEP
  CONCAT CON COPYCOMMIT COPYTYPECHECK DEFINE DEF DESCRIBE ECHO EDITFILE
  EMBEDDED EMB ERRORDETAILS ERRORLOGGING ESCAPE ESC ESCCHAR EXITCOMMIT
  EXITC FEEDBACK FEED FLAGGER FLUSH HEADING HEA HEADSEP HEADS INSTANCE
  LINESIZE LINES LIN LOBOFFSET LOBPREFETCH LOGSOURCE LONG LONGCHUNKSIZE
  LONGC MARKUP MARK NEWPAGE NEWP NULL NUMFORMAT NUMF NUMWIDTH NUMW PAGESIZE
  PAGES PAUSE PAU RECSEP RECSEPCHAR ROWLIMIT ROWPREFETCH SECUREDCOL
  SERVEROUTPUT SERVEROUT SERVEROUTP SHIFTINOUT SHOWMODE SQLBLANKLINES
  SQLBL SQLCASE SQLC SQLCONTINUE SQLCO SQLNUMBER SQLN SQLPLUSCOMPATIBILITY
  SQLPLUSCOMPAT SQLPREFIX SQLPRE SQLPROMPT SQLP SQLTERMINATOR SQLT
  STATEMENTCACHE SUFFIX SUF TAB TERMOUT TERM TIME TI TIMING TIMI TRIMOUT
  TRIM TRIMSPOOL TRIMS UNDERLINE UND VERIFY VER WRAP WRA
`)

/** ¿`palabra` (en mayúsculas) es reservada en el motor `d`? */
export function esReservada(palabra: string, d: DialectoSql): boolean {
  // `deDialecto` y no `RESERVADAS[d]`: con un dialecto desconocido, un error con nombre.
  return deDialecto(RESERVADAS, d).has(palabra.toUpperCase())
}
