// =============================================================================
// PostgreSQL: de las filas de `pg_catalog` a los tipos del contrato (columnas, restricciones,
// índices, FK y fuente) y la tabla relkind -> tipo de objeto. Puro; lo ensambla
// `catalogoPostgres.ts` y lo usa `verDdlPostgres.ts`. No importa `catalogoSql.ts` (ciclos).
// =============================================================================

import type {
  DbColumnaInfo,
  DbFk,
  DbFuente,
  DbIndiceInfo,
  DbRefObjeto,
  DbRelacionesFk,
  DbRestriccionInfo,
  DbTipoObjeto
} from '../../../../shared/db-explorador-ipc.ts'
import { citar } from '../../../../shared/sql/identificadoresSql.ts'
import {
  aBool,
  aLista,
  aNumero,
  AVISO_SIN_FUENTE,
  clasificarFk,
  texto,
  textoOpcional,
  TIPO_RESTRICCION
} from './filasCatalogo.ts'
import type { DialectoCatalogo, FilaCatalogo } from './tipos.ts'

const IDENTIDAD_PG: Record<string, string> = {
  a: 'GENERATED ALWAYS AS IDENTITY',
  d: 'GENERATED BY DEFAULT AS IDENTITY'
}

/** relkind de PG -> tipo de objeto del contrato. */
export const TIPO_RELKIND_PG: Record<string, DbTipoObjeto> = {
  r: 'tabla',
  p: 'tabla',
  v: 'vista',
  m: 'vistaMaterializada',
  f: 'tablaForanea',
  S: 'secuencia',
  F: 'rutina'
}

/** Filas de `sqlColumnas` -> columnas del detalle, con la posición en la PK ya incluida. */
export function mapearColumnas(filas: readonly FilaCatalogo[]): DbColumnaInfo[] {
  const columnas: DbColumnaInfo[] = []
  for (const f of filas) {
    const col: DbColumnaInfo = {
      nombre: texto(f[0]),
      posicion: aNumero(f[4]) ?? columnas.length + 1,
      tipo: texto(f[1]),
      nullable: aBool(f[2]),
      pk: aNumero(f[8])
    }
    const expr = textoOpcional(f[3])
    const identidad = IDENTIDAD_PG[texto(f[6]).trim()]
    // Una columna generada guarda su EXPRESIÓN en pg_attrdef: sin esto parecería un valor por
    // defecto que el usuario puede sobrescribir, y no puede.
    if (texto(f[7]).trim() === 's' && expr !== undefined) col.porDefecto = `GENERATED ALWAYS AS (${expr}) STORED`
    else if (identidad) col.porDefecto = identidad
    else if (expr !== undefined) col.porDefecto = expr
    const comentario = textoOpcional(f[5])
    if (comentario !== undefined) col.comentario = comentario
    columnas.push(col)
  }
  return columnas
}

/** Filas de `sqlRestricciones` (una por restricción) -> restricciones. */
export function mapearRestricciones(filas: readonly FilaCatalogo[]): DbRestriccionInfo[] {
  const salida: DbRestriccionInfo[] = []
  for (const f of filas) {
    const tipo = TIPO_RESTRICCION[texto(f[1]).trim()]
    if (!tipo) continue
    const r: DbRestriccionInfo = { nombre: texto(f[0]), tipo, columnas: aLista(f[3]) }
    const definicion = textoOpcional(f[2])
    if (definicion !== undefined) r.definicion = definicion
    const tabla = textoOpcional(f[5])
    if (tipo === 'fk' && tabla !== undefined) {
      r.referencia = { esquema: texto(f[4]), tabla, columnas: aLista(f[6]) }
    }
    salida.push(r)
  }
  return salida
}

/** Filas de `sqlIndices` -> índices con su definición. */
export function mapearIndices(filas: readonly FilaCatalogo[]): DbIndiceInfo[] {
  return filas
    .filter((f) => texto(f[0]) !== '')
    .map((f) => {
      const i: DbIndiceInfo = { nombre: texto(f[0]), unico: aBool(f[1]), columnas: aLista(f[4]) }
      const definicion = textoOpcional(f[5])
      if (definicion !== undefined) i.definicion = definicion
      return i
    })
}

/** Filas de `sqlFks` -> relaciones: la única consulta basta, las columnas vienen en sus arrays. */
export function mapearFks(esquema: string, objeto: string, filas: readonly FilaCatalogo[]): DbRelacionesFk {
  const r: DbRelacionesFk = { salientes: [], entrantes: [] }
  for (const f of filas) {
    const fk: DbFk = {
      nombre: texto(f[0]),
      desde: { esquema: texto(f[1]), tabla: texto(f[2]), columnas: aLista(f[3]) },
      hacia: { esquema: texto(f[4]), tabla: texto(f[5]), columnas: aLista(f[6]) }
    }
    clasificarFk(fk, esquema, objeto, r)
  }
  return r
}

/** Filas de `sqlFuente` -> la definición de la vista o la rutina, con su origen. */
export function mapearFuente(_d: DialectoCatalogo, ref: DbRefObjeto, filas: readonly FilaCatalogo[]): DbFuente {
  const cabecera = `${citar(ref.esquema)}.${citar(ref.nombre)}`
  const valor = filas.length > 0 ? textoOpcional(filas[0][0]) : undefined
  let origen: string
  let prefijo = ''
  if (ref.tipo === 'rutina') {
    origen = 'pg_get_functiondef'
  } else {
    origen = 'pg_get_viewdef'
    prefijo =
      ref.tipo === 'vista' ? `CREATE OR REPLACE VIEW ${cabecera} AS\n` : `CREATE MATERIALIZED VIEW ${cabecera} AS\n`
  }
  if (valor === undefined) return { partes: [], origen, aviso: AVISO_SIN_FUENTE }
  return { partes: [{ titulo: 'Definición', texto: prefijo + valor }], origen }
}
